# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - HDSpaceX

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup node.js env
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: '16.x'
          
      - name: React - Install dependencies
        working-directory: react
        run: yarn install --network-timoeout 1000000000
        
      - name: React - Yarn Build
        working-directory: react
        run: yarn build
        
      - name: React - Move Published Build
        run: |
          mkdir -p dotnet/Web.Api/ClientApp/
          mv ./react/build dotnet/Web.Api/ClientApp
      - name: DotNet - Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
          include-prerelease: true
      - name: DotNet - Install Dependencies and Restore
        working-directory: dotnet
        run: dotnet restore HDMSpaceX.sln
        
      - name: DotNet - Build
        run: dotnet build HDMSpaceX.sln --configuration Release

      - name: DotNet - Publish
        run: dotnet publish dotnet/HDMSpaceX -c Release -o ${{env.DOTNET_ROOT}}/HDMSpaceX

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/HDMSpaceX

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'HDSpaceX'
          slot-name: 'production'
          publish-profile:  ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
